name: CI Tests

on:
  push:
    paths:
      - "sourcelib/**"
      - "tests/**"
      - .github/workflows/tests.yml
      - .github/workflows/ci_tests.yml
      - pyproject.toml
      - "!sourcelib/_version.py"
      
  pull_request:
    paths:
      - "dicfg/**"
      - "tests/**"
      - .github/workflows/tests.yml
      - .github/workflows/ci_tests.yml
      - pyproject.toml
      - "!sourcelib/_version.py"

jobs:
  call-tests:

    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-ci-test
      cancel-in-progress: true

    uses: ./.github/workflows/tests.yml
